<a href="https://colab.research.google.com/github/EspinosaReyesNataliaMarisol/M-todos-Num-ricos-I/blob/main/pivoteoparcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PIVOTEO PARCIAL  
##ALUMNA: ESPINOSA REYES NATALIA MARISOL

In [1]:
import numpy as np #manipular matrices y realizar cálculos numéricos

def pivparcial(A): #Define la función pivparcial, que toma como entrada una matriz aumentada

    n = A.shape[0]  # Número de filas de la matriz

    print("Matriz Aumentada Inicial:")
    print(A)


    for i in range(n): # Proceso de Eliminación Gaussiana con Pivoteo Parcial
        # Encontrar el mayor pivote absoluto en la columna actual
        max_row_index = np.argmax(abs(A[i:, i])) + i
        if A[max_row_index, i] == 0:
            raise ValueError("El sistema no tiene solución única (pivote nulo encontrado).")

        if i != max_row_index: #Intercambiar la fila actual con la fila del mayor pivote
            A[[i, max_row_index]] = A[[max_row_index, i]]

        for j in range(i + 1, n): # Eliminar los elementos debajo del pivote
            factor = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - factor * A[i, i:]

        print(f"\nMatriz después de la eliminación en la columna {i + 1}:")  # Imprimir la matriz después de la eliminación de cada columna
        print(A)


    x = np.zeros(n)  # Sustitución hacia atrás
    for i in range(n - 1, -1, -1):
        x[i] = (A[i, -1] - np.dot(A[i, i + 1:n], x[i + 1:n])) / A[i, i]
    print("\nMatriz reducida:") # Imprimir
    print(A)

    return x

if __name__ == "__main__": #Define la matriz aumentada A, que combina los coeficientes del sistema y los términos independientes.
    A = np.array([[0.003000, 59.14, 59.17],
                  [5.291, -6.130, 46.78]], dtype=float)  # Definir la matriz aumentada del sistema
    try:
        solucion = pivparcial(A)
        print("\nSolución del sistema:")
        for i in range(len(solucion)):
            print(f"x{i+1} = {solucion[i]:.6f}")
    except ValueError as error:
        print(error)

Matriz Aumentada Inicial:
[[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]]

Matriz después de la eliminación en la columna 1:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Matriz después de la eliminación en la columna 2:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Matriz reducida:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Solución del sistema:
x1 = 10.000000
x2 = 1.000000
